#!/usr/bin/env bash
# Regenerates src/build_info.h with the current git commit SHA, so every
# compiled binary can unambiguously report which commit it came from.
# Run this before every particle compile/flash. Not committed - see
# .gitignore - since it goes stale the instant you commit again.
set -euo pipefail

cd "$(dirname "${BASH_SOURCE[0]}")"

SHA=$(git rev-parse --short HEAD)
DIRTY=""
if ! git diff --quiet || ! git diff --cached --quiet; then
  DIRTY="-dirty"
fi

cat > src/build_info.h << EOF
// Generated by gen-build-info.sh - do not edit, do not commit.
#define GIT_COMMIT_SHA "${SHA}${DIRTY}"
EOF

echo "src/build_info.h -> GIT_COMMIT_SHA=${SHA}${DIRTY}"
