#include "Particle.h"
// Generated by gen-build-info.sh right before each compile/flash - contains
// GIT_COMMIT_SHA for the exact commit this binary was built from. Not
// committed (always regenerated), see .gitignore.
#include "build_info.h"

// We only want Cellular/cloud brought up on wakes where we actually have
// something to report (reed_changed or telemetry) - AUTOMATIC would instead
// have Device OS reconnect the cloud session on every wake regardless.
// SEMI_AUTOMATIC leaves connecting entirely to explicit Particle.connect()
// calls in loop() below.
SYSTEM_MODE(SEMI_AUTOMATIC);

// Bump this and git-tag the release commit (e.g. `git tag fw-v2`) each time
// you cut a release, so the console's Firmware/Releases feature and git
// history both have a matching number. GIT_COMMIT_SHA (logged/published at
// boot, below) pins the exact commit unambiguously either way.
const int FIRMWARE_VERSION = 29;
PRODUCT_VERSION(FIRMWARE_VERSION)

// Run the application and system concurrently in separate threads

// Show system, cloud connectivity, and application logs over USB
// View logs with CLI using 'particle serial monitor --follow'
static SerialLogHandler logHandler(LOG_LEVEL_INFO);

// Reed switch input. It shorts the pin to GND when closed, so the reading
// is an active-low one against the internal pull-up.
//
// That pull-up (~13k typ on nRF52840, so ~VDD/13k =~ 250uA while the reed is
// closed) now stays enabled continuously instead of being switched on around
// each sample. The pin doubles as a sleep wake source - see
// sleepWithCellularOff() - and the nRF52840's GPIO SENSE/DETECT logic needs a
// defined level on the pin for the whole sleep window to fire at all, which
// is the entire time between polls. Toggling the pull-up around the sample
// would therefore save nothing and just break the wake, so the ~250uA is the
// standing price of reporting transitions the moment they happen rather than
// up to WAKE_INTERVAL_MS later.
static const pin_t REED_PIN = D6;

static bool readReedIsClosed() { return !digitalRead(REED_PIN); }

// Upper bound on how long we stay asleep with nothing to do. A reed
// transition wakes us immediately (see sleepWithCellularOff()), so this is
// only the fallback cadence: it re-polls the switch in case an edge was ever
// missed, and it's what paces the telemetry check below.
const unsigned long WAKE_INTERVAL_MS = 60 * 1000;

// Full telemetry (reed/cellular/battery) is cheaper to send less often than
// we poll the reed switch. It goes out on a fleet-wide slot grid rather than
// on a timer relative to the last report (see currentTelemetrySlot()), which
// buys two things that matter once there are thousands of these deployed:
//
//  - Every device has a known reporting time, so a missed report shows up on
//    the back end within one period instead of via a "it has been quiet for a
//    while" heuristic.
//  - The grid is absolute, so an OTA rollout, a site-wide power-up or a
//    recovery after an outage doesn't leave thousands of devices with their
//    timers in phase, all reaching for the same cells at once. A boot-relative
//    timer has exactly that failure mode: whatever restarts the fleet together
//    also aligns it, and it stays aligned until the next restart.
//
// Slot boundaries are epoch-aligned: the Unix epoch starts at midnight UTC and
// this period divides a day evenly, so they fall on 00/06/12/18 UTC.
//
// This is the one knob worth turning to watch the whole cycle on a bench -
// drop it to a few minutes and every derived constant below follows it down on
// its own, so a short period stays as coherent as the production one and there
// is no debug build to remember to undo. Pick a divisor of 86400 to keep the
// grid landing on round times of day; nothing breaks if you don't, the
// boundaries just drift across the day.
const uint32_t TELEMETRY_PERIOD_S = 6UL * 60 * 60;

// Width of the window each device's own offset is drawn from. Wide enough that
// a few thousand devices start their connects a couple per second rather than
// together, narrow enough that "the reporting window" is still a specific half
// hour for whoever is watching the fleet. Note that a slot is when a device
// starts its connect, not when the event lands: registration takes anywhere
// from seconds to MAX_CONNECT_WAIT_MS, so back-end alerting on a missed report
// needs a tolerance in the tens of minutes, not in the minute the slot names.
//
// Clamped to the period, and that clamp is load-bearing rather than defensive.
// currentTelemetrySlot() corrects by exactly one period when `now` hasn't
// reached this device's offset yet, and that correction only lands inside the
// current period while the offset is smaller than the period. Let the window
// exceed it - which is what a period shortened for bench work would do against
// a fixed 30 minutes - and every slot it computes sits in the future: reports
// still come out roughly once per period, so it looks like it works, while the
// grid underneath has quietly stopped meaning anything.
const uint32_t TELEMETRY_WINDOW_TARGET_S = 30UL * 60;
const uint32_t TELEMETRY_WINDOW_S =
    TELEMETRY_WINDOW_TARGET_S < TELEMETRY_PERIOD_S ? TELEMETRY_WINDOW_TARGET_S
                                                   : TELEMETRY_PERIOD_S;
// Cadence used only while the clock has never been synced - a device that has
// just been powered up has no idea where it sits in the grid until its first
// cloud connection. Same period, just measured from the last report.
const unsigned long TELEMETRY_INTERVAL_MS = TELEMETRY_PERIOD_S * 1000UL;

// Attempts a telemetry report gets inside its own slot before it is dropped in
// favour of the next one. Telemetry, unlike a reed transition, is not worth
// chasing: the next slot's report carries the same fields, only fresher.
const int TELEMETRY_MAX_ATTEMPTS = 3;
// Gap between connect attempts, for telemetry and for reed delivery alike. The
// modem is fully powered down in between (see sleepOrIdle()), which is half
// the point - the other half is that nothing about a network that has just
// refused us changes in the seconds after it did.
//
// Capped so that a slot's whole run of attempts still fits inside a period,
// which is what makes "three tries, then wait for the next slot" mean anything.
// At the production period the cap is nowhere near binding (6h/3 = 2h against
// 15 minutes) and this is exactly the 15 minutes asked for; shorten the period
// for bench work and the gap comes down with it instead of a single failure
// swallowing five slots.
const unsigned long RETRY_INTERVAL_TARGET_MS = 15UL * 60 * 1000; // 15 minutes
const unsigned long RETRY_INTERVAL_CAP_MS =
    TELEMETRY_INTERVAL_MS / TELEMETRY_MAX_ATTEMPTS;
const unsigned long RETRY_INTERVAL_MS =
    RETRY_INTERVAL_TARGET_MS < RETRY_INTERVAL_CAP_MS ? RETRY_INTERVAL_TARGET_MS
                                                     : RETRY_INTERVAL_CAP_MS;
// How long a single connect attempt gets before we power-cycle the modem and
// start a fresh one. We no longer give up and sleep on a failed connect (see
// loop()) - as long as something is queued to report, attempts just keep
// coming - so this is a per-attempt budget, not a per-wake one.
//
// It sits deliberately above Device OS's own REGISTRATION_TIMEOUT of 10
// minutes, at which it resets the modem as a last resort. Its escalation
// ladder (AT+COPS=0,2 PLMN reselection once registration goes sticky, an RF
// reset via CFUN cycling when it is denied, then that modem reset) is
// strictly better informed than our blunt power-cycle, so we let it run to
// the end before starting over ourselves. Nothing in the connect path blocks
// for long on our side - the only AT command we send ourselves is a fast
// +COPS read - so this budget is honoured as written.
const unsigned long MAX_CONNECT_WAIT_MS = 12UL * 60 * 1000; // 12 minutes

// Safety cap on how long loop() will hold the connection open for an
// in-flight OTA transfer (see g_otaInProgress below). The binary itself is
// tiny (well under 30KB), so this is a generous margin - if firmware_update
// somehow never reports complete/failed (e.g. the transfer stalls), we
// still need to give up eventually instead of never sleeping again.
const unsigned long MAX_OTA_WAIT_MS = 5UL * 60 * 1000; // 5 minutes

// How long to keep the connection open after we're done publishing before
// actually disconnecting. The cloud decides whether to push a pending OTA
// update asynchronously, and firmware_update_begin (see g_otaInProgress)
// is delivered via the system thread with some latency - disconnecting the
// instant our own publish call returns risks tearing the connection down
// right as a push is starting, before the flag has had a chance to flip.
const unsigned long POST_REPORT_LINGER_MS = 3UL * 1000; // 3 seconds

static float readBatteryVoltage() {
  const pin_t VBAT_MEAS_PIN = A0;
  const float ADC_REF_VOLTAGE = 3.3f;
  const float ADC_MAX_COUNTS = 4095.0f;
  const float VBAT_DIVIDER_RATIO = (2940.0f + 442.0f + 2940.0f) / (2940.0f);
  float adcVoltage =
      (analogRead(VBAT_MEAS_PIN) / ADC_MAX_COUNTS) * ADC_REF_VOLTAGE;
  return adcVoltage * VBAT_DIVIDER_RATIO;
}

// Estimates remaining charge from battery voltage.
//
// CURVE is calibrated from an actual full discharge of this hardware: a fresh
// pair of CR123A cells run from installation to device death (2026-08-13
// 19:07 to 2026-08-17 01:39 UTC, 78.5 hours, 857 telemetry reports at the
// production ~5.5-minute cadence, fw v22 / c71a084). Ground truth per sample
// is the fraction of total runtime remaining at that moment - the cadence is
// constant, so elapsed time tracks consumed charge - and the table pairs each
// voltage with the median truth of all samples seen at that voltage. So the
// output answers "what fraction of the observed service life is left on this
// board", with the divider, boost-converter load profile and reporting duty
// cycle all baked in, rather than quoting a datasheet cell.
//
// Input must be vBatLoad (sampled while the modem is up and drawing): the
// calibration run logged that reading, and publishTelemetry() feeds it here.
//
// The chemistry caps accuracy at the top. A fresh pack sags from 6.4V to
// ~5.72V within the first half hour, then *recovers* to ~5.81V and only
// passes 5.72V again near 40% - so any reading in the 5.70-5.81V band is
// ambiguous between ~95% and ~40%, and the table resolves it with the median
// (most samples at those voltages were mid-life). That ambiguity is why this
// function is no longer called directly for telemetry: above 5.68V
// batteryPercentEstimate() ignores this table entirely and counts the
// modem's charge instead, which does distinguish the two ends of the band.
// Below ~5.6V the curve steepens and voltage alone is within a couple of
// percent of truth, and that is the region this table is kept for.
//
// The pack died within an hour of reporting 2.96V, so the 2.90V floor is the
// real cliff edge, not a theoretical cell cutoff.
static int batteryPercentFromVoltage(float vbat) {
  // Pack voltage of 2xCR123A in series, exactly as readBatteryVoltage()
  // reports it - the calibration was done on the assembled pack, so per-cell
  // figures never enter into it.
  struct CurvePoint {
    float volts;
    uint8_t percent;
  };
  static const CurvePoint CURVE[] = {
      {6.40f, 100},
      {5.90f, 99},
      // fresh-sag/recovery ambiguity band: median-of-samples mapping
      {5.80f, 72},
      {5.75f, 64},
      {5.70f, 41},
      // steady decline - this is where the estimate is trustworthy
      {5.65f, 35},
      {5.60f, 30},
      {5.50f, 25},
      {5.40f, 20},
      {5.30f, 16},
      {5.20f, 13},
      {5.10f, 11},
      {5.00f, 10},
      {4.90f, 8},
      {4.75f, 7},
      {4.60f, 6},
      {4.45f, 5},
      {4.30f, 4},
      {4.05f, 3},
      {3.75f, 2},
      {3.30f, 1},
      {2.90f, 0},
  };
  const size_t COUNT = sizeof(CURVE) / sizeof(CURVE[0]);

  if (vbat >= CURVE[0].volts) {
    return 100;
  }
  if (vbat <= CURVE[COUNT - 1].volts) {
    return 0;
  }

  int ret = 0;
  for (size_t i = 1; i < COUNT; i++) {
    if (vbat >= CURVE[i].volts) {
      // Interpolate within the bracketing pair. The divisor can't be zero:
      // the table's voltages strictly decrease.
      float span = CURVE[i - 1].volts - CURVE[i].volts;
      float frac = (vbat - CURVE[i].volts) / span;
      float pct = CURVE[i].percent +
                  frac * ((float)CURVE[i - 1].percent - CURVE[i].percent);
      ret = (int)(pct + 0.5f);
      break;
    }
  }

  if (ret > 100)
    return 100;
  if (ret < 0)
    return 0;
  return ret;
}

// Battery estimate that resolves the voltage table's blind spot by counting
// the charge the modem has drawn.
//
// Voltage and coulombs are each blind where the other sees, and the split is
// AMBIGUOUS_BAND_LOW_V:
//   <  5.68V - the discharge curve has steepened, voltage tracks truth to
//              within a percent or two, and it is measured rather than
//              modelled: it stays right whatever the cells' real capacity
//              turns out to be, and whatever the modem actually drew
//   >= 5.68V - the Li-MnO2 plateau, where voltage says almost nothing. The
//              pack passes 5.72V both while fresh (sagging in) and again
//              near 40%, so a reading here is ambiguous over more than half
//              the pack's life. Charge drawn is the only signal left
//
// This replaces g_cloudConnectAttemptsCount, which was a coulomb counter
// only by accident: it counted cycles, and the calibration pack happened to
// deliver 868 of them. A cycle is not a fixed amount of charge. The same
// firmware measured 45s cold-start cycles on a good cell and a 240s
// registration stall on a bad one - a 5x spread that a cycle count reports
// as one tick either way, while the phase timers see all of it.
//
// Each timer gets its own current, because the three are genuinely different
// regimes and the spread between them is wide: on one PPK trace the modem
// averaged 187mA registered against 72mA on its way down, a factor of 2.6
// that a single constant would have to split the difference on.
//
// The constants are the worst figure each phase produced across four PPK
// captures, not the typical one - "full power", as the pack should be
// budgeted. The reason the worst and the typical differ so much is a carrier
// re-steer that happened mid-test: the SARA-R510S moved from T-Mobile to
// AT&T, RSRQ fell from -13.5 to -17.5dB, and Cat-M1 answered by repeating
// transmissions until a fixed-size DTLS handshake took 4148ms instead of
// 211ms. That is the same 1.5-2x on current, and nothing in the firmware
// chooses it or can see it coming. So the budget assumes it is always the
// case:
//
//   phase      T-Mobile      AT&T      constant
//   search     169  139      213  159    215mA
//   ready      187  213      364  339    365mA
//   offgoing    72  126      218  247    250mA
//
// (two captures per carrier; integrated over exactly the intervals these
// timers count, taken from the phase-transition log lines, aligned to the
// current trace by cross-correlating the modem-active window)
//
// On a good cell the gauge therefore falls roughly twice as fast as the pack
// really empties, bottoms out at the 38% floor, and hands over to voltage.
// It reports the pack pessimistically, never optimistically.
//
// What this does NOT count is the sleeping board, ~0.4mA, which at the
// 12-hour field cadence is comparable to the modem's own share. The estimate
// is a modem-airtime budget by construction; fold in an idle term once a
// full discharge run on the final configuration says what the baseline
// really is with the reed open.
//
// The timers read "on this pack" only because a battery swap cuts power and
// retained SRAM does not survive that. If a pack is ever swapped with the
// counters intact the estimate reads low, but it drops out of the picture as
// soon as the pack leaves the plateau, and the floor keeps it from ever
// claiming near-dead on a healthy cell.
static int batteryPercentEstimate(float vbat, uint64_t searchMs,
                                  uint64_t readyMs, uint64_t offgoingMs) {
  // Nominal capacity of the pack. The two CR123A cells are in series, so the
  // pack carries one cell's capacity at twice the voltage, not two cells'.
  static const float PACK_CAPACITY_MAH = 1500.0f;
  // Per-phase currents, worst measured. See the table above.
  static const float SEARCH_MA = 215.0f;
  static const float READY_MA = 365.0f;
  static const float OFFGOING_MA = 250.0f;
  static const float AMBIGUOUS_BAND_LOW_V = 5.68f;

  if (vbat < AMBIGUOUS_BAND_LOW_V) {
    return batteryPercentFromVoltage(vbat);
  }

  float usedMah = ((float)searchMs * SEARCH_MA + (float)readyMs * READY_MA +
                   (float)offgoingMs * OFFGOING_MA) /
                  3600000.0f;
  float pct = 100.0f * (1.0f - usedMah / PACK_CAPACITY_MAH);
  // Voltage this high was never observed below ~37% on the calibration pack,
  // so a budget that claims less has drifted - stale timers, a longer-lived
  // pack, or a kinder carrier than the constant assumes. Voltage wins.
  if (pct < 38.0f)
    pct = 38.0f;
  if (pct > 100.0f)
    pct = 100.0f;
  return (int)(pct + 0.5f);
}

// Prints raw AT command responses as they arrive
static int atCallback(int type, const char *buf, int len, void *data) {
  if (buf) {
    Log.info("%.*s", len, buf);
  }
  return WAIT;
}

static retained uint32_t g_cloudConnectAttemptsCount = 0;
static retained uint32_t g_cloudConnectSuccesses = 0;

// Modem-on time on this battery pack, split by phase, in milliseconds.
//
// Charge is spent per unit time, not per connect, and the two phases cost
// very different amounts: searching and registering runs the transmitter
// at high power in bursts, while a registered modem with the interface up
// sits in the low milliamps. A cycle that gives up at MAX_CONNECT_WAIT_MS
// burns eight minutes of the expensive kind, one that connects straight
// away burns seconds of it, and g_cloudConnectAttemptsCount counts both as
// 1 - which is why it only works as a charge proxy for as long as the
// per-cycle radio cost stays close to what the calibration run saw. These
// two are published alongside it (see publishTelemetry()) so the next
// discharge run can be replayed against elapsed modem time instead.
//
// Same "on this pack" semantics as the connect counters above, and for the
// same reason: retained SRAM doesn't survive the power cut of a battery
// swap. Milliseconds in 64 bits so nothing here has to reason about
// wraparound - System.millis() is 64-bit too, unlike the global millis().
// Three phases, not two, because the teardown is neither of the others.
// AT+CFUN=0 (the network detach) alone measures 17.4-19.8s in every single
// session, and until it was split out it landed in the search bucket - on a
// healthy cycle that made roughly two thirds of "searching" actually be the
// modem shutting down, at nothing like search current. Fitting a search
// current against that would have reproduced exactly the flaw this replaced.
static retained uint64_t g_modemSearchMs = 0;   // powered, not registered yet
static retained uint64_t g_modemReadyMs = 0;    // registered, interface up
static retained uint64_t g_modemOffgoingMs = 0; // detaching and powering down

enum ModemPhase {
  MODEM_OFF = 0,
  MODEM_SEARCH,
  MODEM_READY,
  MODEM_OFFGOING,
};

// Phase state behind the counters above. Only ever touched from the
// application thread - see networkStatusHandler() - but volatile because
// the handler runs from the thread's async queue, which is pumped from
// inside delay()/Particle.process()/Future::wait() as well as between
// loop() iterations. So a phase can change part-way through a function
// here, just not part-way through a statement.
static volatile ModemPhase s_modemPhase = MODEM_OFF;
static volatile uint64_t s_modemPhaseStartMs = 0;

static const char *modemPhaseName(ModemPhase phase) {
  switch (phase) {
  case MODEM_SEARCH:
    return "search";
  case MODEM_READY:
    return "ready";
  case MODEM_OFFGOING:
    return "offgoing";
  default:
    return "off";
  }
}

// Credits the time since the last phase change to the counter for the
// phase we were in, then restarts the clock. Credits nothing while the
// modem is off, so it's safe to call at any point.
static void modemTimeAccrue(uint64_t now) {
  uint64_t elapsed = now - s_modemPhaseStartMs;
  switch (s_modemPhase) {
  case MODEM_SEARCH:
    g_modemSearchMs += elapsed;
    break;
  case MODEM_READY:
    g_modemReadyMs += elapsed;
    break;
  case MODEM_OFFGOING:
    g_modemOffgoingMs += elapsed;
    break;
  default:
    break;
  }
  s_modemPhaseStartMs = now;
}

// Closes the current phase, opens the next, and logs the transition.
//
// The log line exists to be lined up against an external current trace: the
// timestamp Device OS prefixes to it is the boundary, and `event` names the
// Device OS event that caused it, so a step in the current can be attributed
// without guessing. The running totals are only printed on the way to OFF,
// where the line costs nothing - every log call blocks until the USB CDC
// write drains, and inside the connect path that time is itself being
// measured.
static void modemPhaseSet(uint64_t now, ModemPhase next, const char *event) {
  ModemPhase prev = s_modemPhase;
  uint64_t elapsed = now - s_modemPhaseStartMs;
  modemTimeAccrue(now);
  s_modemPhase = next;

  if (prev == MODEM_OFF) {
    Log.info("modem %s: -> %s", event, modemPhaseName(next));
  } else if (next == MODEM_OFF) {
    Log.info("modem %s: %s -> off (+%lu ms) | totals search=%lu ready=%lu "
             "offgoing=%lu ms",
             event, modemPhaseName(prev), (unsigned long)elapsed,
             (unsigned long)g_modemSearchMs, (unsigned long)g_modemReadyMs,
             (unsigned long)g_modemOffgoingMs);
  } else {
    Log.info("modem %s: %s -> %s (+%lu ms)", event, modemPhaseName(prev),
             modemPhaseName(next), (unsigned long)elapsed);
  }
}

// Phase changes we cause ourselves are stamped at the call site (see
// Particle.connect() and Cellular.off() below); this handler covers the
// ones Device OS makes on its own initiative - the RF reset via CFUN
// cycling when registration is denied, and the modem reset at its
// 10-minute REGISTRATION_TIMEOUT, both power the modem without being
// asked - and acts as a fallback for the rest.
//
// It cannot be the primary source, because Device OS delivers these events
// through the application thread's queue one per pump, and the queue is
// pumped once per SPARK_LOOP_DELAY_MILLIS. A teardown emits four events
// inside 16ms and they then arrive a second apart: measured on a real
// session, powering_off was raised at 26184ms and handled at 32168ms, six
// seconds late. Left to the events alone the offgoing bucket came out 32%
// short with the difference credited to search - which is exactly the kind
// of error these counters exist to avoid.
//
// Hence the guards below: a late event must never drag the phase backwards
// out of one the call site has already set.
//
// network_status_on/off are tied to the interface's real PHY state
// (NetworkManager::handleIfPhyState in Device OS), i.e. to the modem
// actually being powered, but they arrive after the powering_on/
// powering_off transitions - and powering up is itself part of the cost,
// so the clock starts at powering_on and keeps running through the
// (~19s, see sleepWithCellularOff()) power-down until off arrives.
//
// network_status_connected has no call-site equivalent - only Device OS
// knows when registration and PPP have actually completed - so it stays the
// primary source for that one boundary. It is also the least affected: it
// arrives on its own rather than in a burst, so the lag is one pump at most.
//
// The events that don't move a phase are still logged, because they are free
// markers to line a current trace up against - network_status_on in
// particular would be the moment the modem is genuinely powered, though on
// this platform it never fires: Device OS only emits it while networkStatus_
// is still POWERING_ON, and that state is left 3ms later, long before the
// interface PHY comes up (system_network_manager.cpp).
static void networkStatusHandler(system_event_t event, int param) {
  uint64_t now = System.millis();
  switch (param) {
  case network_status_powering_on:
    // Fallback only: a connect we started stamps this at the call site, but
    // Device OS also powers the modem on its own after a registration
    // timeout, and that has to be caught somewhere.
    if (s_modemPhase == MODEM_OFF) {
      modemPhaseSet(now, MODEM_SEARCH, "powering_on");
    }
    break;
  case network_status_connected:
    modemPhaseSet(now, MODEM_READY, "connected");
    break;
  case network_status_disconnecting:
    // Genuinely means "back to searching" only when the link dropped on us.
    // In a teardown it arrives after Cellular.off() has already moved us to
    // offgoing, and must not undo that.
    if (s_modemPhase == MODEM_READY) {
      modemPhaseSet(now, MODEM_SEARCH, "disconnecting");
    }
    break;
  case network_status_powering_off:
    // Fallback: the teardown we start ourselves is stamped at Cellular.off().
    if (s_modemPhase != MODEM_OFFGOING && s_modemPhase != MODEM_OFF) {
      modemPhaseSet(now, MODEM_OFFGOING, "powering_off");
    }
    break;
  case network_status_off:
    modemPhaseSet(now, MODEM_OFF, "off");
    break;
  case network_status_on:
    Log.info("modem on (interface powered)");
    break;
  case network_status_connecting:
    Log.info("modem connecting");
    break;
  case network_status_disconnected:
    Log.info("modem disconnected");
    break;
  default:
    break;
  }
}

// Cellular.command() hands each reply line to a callback rather than
// returning it, so pull the one field we need - <mode> out of
// "+COPS: <mode>,<format>,<oper>,<AcT>" - in place, and return it through
// the context pointer. Matching on the "+COPS:" prefix rather than the
// whole line keeps this indifferent to leading CRLF and to a URC sharing
// the reply. Left untouched (so, negative) when no such line arrives, which
// the caller reads as "no answer".
static int copsModeCallback(int type, const char *buf, int len, int *mode) {
  if (buf && mode) {
    const char *cops = strstr(buf, "+COPS:");
    if (cops) {
      sscanf(cops, "+COPS: %d", mode);
    }
  }
  return WAIT;
}

// Names for the access technologies this board can actually report, so a
// serial capture does not need net_hal.h open beside it.
static const char *accessTechName(int rat) {
  switch (rat) {
  case NET_ACCESS_TECHNOLOGY_GSM:
    return "GSM";
  case NET_ACCESS_TECHNOLOGY_EDGE:
    return "EDGE";
  case NET_ACCESS_TECHNOLOGY_UMTS:
    return "UMTS";
  case NET_ACCESS_TECHNOLOGY_LTE:
    return "LTE";
  case NET_ACCESS_TECHNOLOGY_LTE_CAT_M1:
    return "LTE-M";
  case NET_ACCESS_TECHNOLOGY_LTE_CAT_NB1:
    return "NB-IoT";
  default:
    return "unknown";
  }
}

// Everything Device OS knows about the radio, in one line per report.
//
// This exists because a session where every active phase drew 1.5-2x more
// current than the one before it took an hour to explain, and the answer -
// the SIM had re-steered to another carrier whose cell was ~3.5dB worse on
// RSRQ - was invisible in the log. Signal *strength* was unchanged, because
// that is derived from RSRP and RSRP barely moved; what moved was quality,
// and with it the number of Cat-M1 repetitions per transmission. A
// fixed-size DTLS handshake went from 211ms to 4148ms on the same payload.
// So RSRQ in dB is the number to watch, and it was never being written down.
//
// Two Device OS calls, no AT of our own:
//   Cellular.RSSI()            - RAT, RSRP in dBm, RSRQ in dB, and the two
//                                percentages that also reach the cloud
//   cellular_global_identity() - which tower: MCC, MNC, LAC, cell id
//
// What Device OS does not carry, and this therefore cannot log: EARFCN,
// band, channel bandwidth, physical cell id and SINR. cellular_signal_t
// (hal/inc/cellular_hal_constants.h) has fields for RAT, RSRP, RSRQ and the
// percentages, and nothing else - those values only exist inside the modem's
// AT+UCGED reply. Of them only SINR would really be missed, and RSRQ tracks
// it closely enough to tell a good cell from a bad one: across the two
// carriers seen here, RSRQ -13.5dB went with SINR +0.5dB and RSRQ -17.5dB
// with SINR -4dB.
static void logCellularDetails() {
  CellularSignal sig = Cellular.RSSI();

  CellularGlobalIdentity cgi = {};
  cgi.size = sizeof(cgi);
  cgi.version = CGI_VERSION_LATEST;
  if (cellular_global_identity(&cgi, nullptr) == SYSTEM_ERROR_NONE) {
    Log.info("cell mcc=%u mnc=%u lac=0x%04x cid=0x%08lx",
             cgi.mobile_country_code, cgi.mobile_network_code,
             cgi.location_area_code, (unsigned long)cgi.cell_id);
  } else {
    Log.info("cell identity unavailable");
  }

  // getStrengthValue()/getQualityValue() are RSRP in dBm and RSRQ in dB on
  // LTE; the percentages beside them are what the console shows. Both come
  // back negative-or-zero when the modem has nothing to report.
  Log.info("signal rat=%s rsrp=%.0f dBm (%.0f%%) rsrq=%.1f dB (%.0f%%)",
           accessTechName((int)sig.getAccessTechnology()),
           sig.getStrengthValue(), sig.getStrength(), sig.getQualityValue(),
           sig.getQuality());
}

// Migration cleanup for devices that ran a build which pinned the modem to
// one operator with AT+COPS=1. Device OS will not undo that on its own:
// SaraNcpClient::registerNet() only restores automatic selection when the
// modem reports mode 2 (deregistered), gated on
// `if (copsState != 0 && copsState != 1)` with the comment "Only run
// AT+COPS=0 if currently de-registered, to avoid PLMN reselection". Manual
// mode is deliberately left alone, so a modem left pinned to a PLMN that
// has since gone marginal stays pinned right through an OTA.
//
// Reading the mode is one fast command that never triggers a network
// search; the write is only issued when manual mode is actually found.
// Delete this once no device in the field can still be running a build
// that set AT+COPS=1.
//
// Returns true once the modem has given a definitive answer that it is not
// in manual mode, so the caller can stop asking for good. Everything else -
// an unparsable read, or a read that did find manual mode - returns false
// and gets retried on a later session: the write's success doesn't need
// checking, because if it didn't take, the next read still reports mode 1.
static bool restoreAutomaticOperatorSelection() {
  int mode = -1;
  Cellular.command(copsModeCallback, &mode, 10000, "AT+COPS?\r\n");

  if (mode < 0) {
    return false; // no answer - ask again next session
  }
  if (mode != 1) {
    return true; // definitively not manual, nothing left to do
  }
  Log.warn("Modem is in manual operator selection, restoring automatic");
  // Device OS allows 5 minutes for this one (UBLOX_COPS_TIMEOUT), noting
  // that u-blox modems overrun the AT manual's documented 3 min.
  Cellular.command(atCallback, (void *)nullptr, 300000, "AT+COPS=0,2\r\n");
  return false;
}

// Particle.publish() returns a Future<bool> - queued/sent is not the same
// as acknowledged by the cloud. wait(timeout) blocks until the future is
// done or the timeout elapses; isSucceeded()/isFailed() on their own block
// indefinitely if called before the future is actually done, so wait()
// must be called first with an explicit positive timeout.
static bool waitForPublish(particle::Future<bool> &result,
                           const char *eventName, const char *payload) {
  if (!result.wait(5000)) {
    Log.warn("Publish %s timed out waiting for ack: %s", eventName, payload);
    return false;
  }
  if (result.isSucceeded()) {
    Log.info("Published %s: %s", eventName, payload);
    return true;
  }
  Log.warn("Publish %s failed: %s", eventName, payload);
  return false;
}

// Slot whose telemetry the cloud has actually acknowledged, and the slot the
// attempt counter below belongs to. Both retained, along with the counter, so
// that a reset doesn't hand a crash loop a fresh budget of attempts and
// doesn't lose track of where in the grid we are. A battery swap cuts power
// and clears them, which is the behaviour we want - a device that has just
// been opened up should report.
static retained time_t g_telemetrySlotSent = 0;
static retained time_t g_telemetrySlotAttempted = 0;
static retained uint8_t g_telemetryAttempts = 0;

// Forces one telemetry report per boot, ahead of the slot grid and regardless
// of what the retained bookkeeping above says about the current slot.
//
// Not retained, and nothing in the sleep path reboots - ULTRA_LOW_POWER
// resumes execution rather than restarting (see sleepWithCellularOff()) - so
// this is set exactly once per power-up or reset, not once per wake.
//
// It overrides the slot bookkeeping on purpose: after a reset mid-window we
// report again even though that slot's report already landed. The duplicate
// costs one event, and it is worth it - a reset is the one thing the fleet
// cannot see from the outside, and "came back up at 09:04" is exactly the
// datapoint that separates a brownout from a device that quietly died.
static bool g_bootTelemetryPending = true;

// Timestamp behind the no-clock fallback cadence (see telemetryOwed()). Not
// retained: after a reset the boot report above re-establishes it anyway.
static unsigned long g_lastTelemetryMillis = 0;

// This device's fixed position inside the reporting window, in seconds.
//
// FNV-1a over the Device ID: no provisioning step and no coordination with the
// cloud, yet the fleet spreads evenly across the window and each device keeps
// the same second for life. That stability is the point - it is what makes
// "this device reports at :17" something the back end can check, and what
// stops the spread from collapsing after an OTA the way a random offset drawn
// at boot would.
//
// Cached because System.deviceID() builds a String on every call and this is
// consulted on every wake.
static uint32_t telemetrySlotOffsetS() {
  static uint32_t cached = UINT32_MAX; // never a real offset - see the modulo
  if (cached == UINT32_MAX) {
    String id = System.deviceID();
    uint32_t hash = 2166136261u;
    for (unsigned int i = 0; i < id.length(); i++) {
      hash ^= (uint8_t)id[i];
      hash *= 16777619u;
    }
    cached = hash % TELEMETRY_WINDOW_S;
    Log.info("Telemetry slot: +%lus into each %lus window, period %lus",
             (unsigned long)cached, (unsigned long)TELEMETRY_WINDOW_S,
             (unsigned long)TELEMETRY_PERIOD_S);
  }
  return cached;
}

// The most recent moment this device was due to report, at or before `now`.
//
// Epoch arithmetic rather than Time.hour()/Time.minute(), which are shifted by
// whatever Time.zone()/DST offset happens to be configured - the grid has to
// be the same one fleet-wide, so it can only ever be UTC.
static time_t currentTelemetrySlot(time_t now) {
  uint32_t secs = (uint32_t)now;
  time_t due = (time_t)(secs / TELEMETRY_PERIOD_S * TELEMETRY_PERIOD_S +
                        telemetrySlotOffsetS());
  if (now < due) {
    // Past the period boundary but not yet at our offset within it, so the
    // slot we are currently owed is still the previous one.
    due -= (time_t)TELEMETRY_PERIOD_S;
  }
  return due;
}

// Whether a telemetry report is owed right now.
//
// The boot report comes first and answers before anything else is consulted -
// a device that has just come up reports, whatever the grid says.
//
// After that: a device that has never had a valid clock (a fresh power-up that
// hasn't reached the cloud yet) has no grid to sit on, so it falls back to the
// boot-relative cadence until the first sync. That first report is itself what
// gets it a clock, after which recordTelemetrySent() pins it to its slot.
static bool telemetryOwed() {
  if (g_bootTelemetryPending) {
    return true;
  }
  if (!Time.isValid()) {
    return millis() - g_lastTelemetryMillis >= TELEMETRY_INTERVAL_MS;
  }
  return currentTelemetrySlot(Time.now()) > g_telemetrySlotSent;
}

// Whether telemetry still has attempts left to spend on powering the modem up
// for its own sake.
//
// While the clock is unsynced the budget doesn't apply: there is no next slot
// to defer to, and a report is the very thing that would get us a clock. That
// only ever matters on a device that has never once reached the cloud.
//
// The boot report draws on the same budget rather than getting its own. If it
// burns all three it isn't dropped - g_bootTelemetryPending stays set, so it
// goes out at the next slot, where telemetryBudgetRollover() has handed the
// attempts back. It just stops keeping the modem busy in the meantime.
static bool telemetryWithinBudget() {
  return !Time.isValid() || g_telemetryAttempts < TELEMETRY_MAX_ATTEMPTS;
}

// Hands the attempt budget back when we roll into a new slot, so a slot that
// was given up on doesn't leave the next one with nothing left to spend.
static void telemetryBudgetRollover() {
  if (!Time.isValid()) {
    return; // no grid yet - telemetryWithinBudget() ignores the counter anyway
  }
  time_t slot = currentTelemetrySlot(Time.now());
  if (slot != g_telemetrySlotAttempted) {
    g_telemetrySlotAttempted = slot;
    g_telemetryAttempts = 0;
  }
}

// Marks the current slot as reported, and retires the boot report along with
// it: whichever of the two this send was for, one report has now landed and
// the next one is due at the next slot. Only called once the cloud has
// actually acknowledged the publish - a report that timed out has to be
// retried, which is the whole reason publishTelemetry() returns a bool.
static void recordTelemetrySent() {
  g_bootTelemetryPending = false;
  g_lastTelemetryMillis = millis();
  g_telemetryAttempts = 0;
  if (Time.isValid()) {
    g_telemetrySlotSent = currentTelemetrySlot(Time.now());
  }
}

// Sent once at boot and then once per telemetry slot (see
// currentTelemetrySlot()) - not on every reed poll, which is far more frequent
// and only needs the radio when the state actually changed. Returns whether
// the cloud acknowledged it: a report that wasn't acknowledged is still owed,
// and the caller spends another of the slot's attempts on it.
//
// Both battery voltages go out because neither alone is enough. vBatIdle is
// sampled at wake before the modem powers up, so it's close to open-circuit;
// vBatLoad is sampled while connected, with the modem drawing. Their
// difference is the drop across the cell's internal resistance, which climbs
// steadily as a primary lithium cell depletes - and that climb is the only
// thing that moves for most of a CR123A's life, since its Li-MnO2 plateau
// keeps the absolute voltage nearly flat (see batteryPercentFromVoltage()).
// So the pair is a better end-of-life signal than either reading is.
//
// `battery` is derived from vBatLoad rather than vBatIdle: the calibration
// curve behind it was logged under load too, so feeding it the loaded
// reading keeps both sides of the comparison consistent. The modem timers
// go in as well - see batteryPercentEstimate() for how they break the flat
// top of the discharge curve.
//
// signalStrength/signalQuality duplicate what the cloud-requested vitals
// (see loop()) already report. That duplication is deliberate: vitals
// arrive as a separate system event that the Ubidots integration can't fold
// into the same webhook, and one event with everything in it beats two
// integrations to maintain. Both are percentages, the same numbers the
// console shows.
// They come through as -1 when the modem can't report a level - passed on
// as-is rather than suppressed, so the consumer sees a value it can filter.
//
// connectAttempts counts sessions we started, connectSuccesses those that
// got far enough to publish and disconnect cleanly. The ratio is the useful
// part: a device that keeps trying and failing burns far more battery than
// one that connects first time, and that shows up here long before it shows
// up as a missed report. Both are `retained` so a reset doesn't zero them.
//
// The three modem*Sec fields are the same story measured in time rather than
// in cycles, and they are what `battery` is computed from above - each
// weighted by its own current, since the phases differ by up to 2.6x. They
// go out individually rather than pre-weighted so that a discharge run can
// re-fit those weights against the pack that actually died, which is the one
// thing telemetry can't reconstruct from a single percentage.
//
// slotOffsetSec makes the schedule self-describing: it is this device's fixed
// second within the reporting window (see telemetrySlotOffsetS()), so the back
// end can say when the next report is due without re-implementing the hash
// against the device ID and getting it subtly wrong.
static bool publishTelemetry(bool reedClosed, float vBatLoad, float vBatIdle,
                             float signalStrength, float signalQuality) {
  // Fold the session we're publishing from into the counters first, so the
  // numbers include this connect instead of lagging a report behind.
  // Nothing between the accrual and the reads pumps the application
  // thread's queue, so networkStatusHandler() can't land in the middle and
  // no locking is needed - keep it that way if anything is inserted here.
  modemTimeAccrue(System.millis());
  uint32_t modemSearchSec = (uint32_t)(g_modemSearchMs / 1000);
  uint32_t modemReadySec = (uint32_t)(g_modemReadyMs / 1000);
  uint32_t modemOffgoingSec = (uint32_t)(g_modemOffgoingMs / 1000);
  int batteryPercentage = batteryPercentEstimate(
      vBatLoad, g_modemSearchMs, g_modemReadyMs, g_modemOffgoingMs);
  String payload = String::format(
      "{"
      "\"reedclosed\":%d,"
      "\"battery\":%d,"
      "\"vBatLoad\":%.3f,"
      "\"vBatIdle\":%.3f,"
      "\"signalStrength\":%.0f,"
      "\"signalQuality\":%.0f,"
      "\"connectAttempts\":%u,"
      "\"connectSuccesses\":%u,"
      "\"modemSearchSec\":%u,"
      "\"modemReadySec\":%u,"
      "\"modemOffgoingSec\":%u,"
      "\"slotOffsetSec\":%u"
      "}",
      reedClosed ? 1 : 0, batteryPercentage, vBatLoad, vBatIdle, signalStrength,
      signalQuality, g_cloudConnectAttemptsCount, g_cloudConnectSuccesses,
      modemSearchSec, modemReadySec, modemOffgoingSec, telemetrySlotOffsetS());
  particle::Future<bool> result =
      Particle.publish("telemetry", payload, PRIVATE);
  return waitForPublish(result, "telemetry", payload.c_str());
}

// Fired immediately (independent of the telemetry cadence) whenever the reed
// switch flips state between wakes. `changedAt` is captured at poll time
// (see enqueueReedTransition()), not at publish time, and rendered via
// Time.timeStr() instead of a raw unix timestamp. Retries a few times in
// place (while we're still connected anyway) - this event is the one thing
// in this firmware that genuinely needs to land, unlike telemetry. Returns
// whether it was actually acknowledged by the cloud, not just attempted.
//
// These in-place retries are seconds apart and only cover a publish failing
// on a connection we already have. Failing to get a connection at all is the
// outer loop's problem: the entry stays queued and loop() opens a fresh
// session every RETRY_INTERVAL_MS, with no cap, until this returns true.
static bool publishReedChanged(bool reedClosed, time_t changedAt) {
  String payload =
      String::format("{\"reedclosed\":%d,\"timestamp\":\"%s\"}",
                     reedClosed ? 1 : 0, Time.timeStr(changedAt).c_str());
  const int MAX_ATTEMPTS = 3;
  for (int attempt = 1; attempt <= MAX_ATTEMPTS; attempt++) {
    particle::Future<bool> result =
        Particle.publish("reed_changed", payload, PRIVATE);
    if (waitForPublish(result, "reed_changed", payload.c_str())) {
      return true;
    }
    if (attempt < MAX_ATTEMPTS) {
      Log.warn("Retrying reed_changed publish (attempt %d/%d)", attempt + 1,
               MAX_ATTEMPTS);
      delay(1000);
    }
  }
  return false;
}

// Queue of reed transitions not yet acknowledged by the cloud. A single
// "pending state" variable isn't enough for a real delivery guarantee: if
// a publish fails and the reed flips back before the next wake, comparing
// against "current state" alone silently loses the transition that failed.
// Each transition is recorded independently, in order, and only removed
// once actually published successfully. retained (not just static) so a
// real device reset (crash, brownout) doesn't drop anything still queued.
struct ReedTransition {
  bool state;
  time_t timestamp; // 0 if Time wasn't synced yet at poll time - resolved at
                    // drain time
};
const int REED_QUEUE_CAPACITY = 16;
static retained ReedTransition g_reedQueue[REED_QUEUE_CAPACITY];
// Index of the oldest undelivered entry.
static retained uint8_t g_reedQueueHead = 0;
// Number of entries currently queued.
static retained uint8_t g_reedQueueCount = 0;

static void enqueueReedTransition(bool state, time_t timestamp) {
  if (g_reedQueueCount >= REED_QUEUE_CAPACITY) {
    // Pathological case (reed toggling faster than we can ever get a
    // connection window) - drop the oldest to bound memory and keep making
    // progress, rather than silently refusing all future transitions.
    Log.error("Reed transition queue full - dropping oldest entry");
    g_reedQueueHead = (g_reedQueueHead + 1) % REED_QUEUE_CAPACITY;
    g_reedQueueCount--;
  }
  uint8_t tail = (g_reedQueueHead + g_reedQueueCount) % REED_QUEUE_CAPACITY;
  g_reedQueue[tail].state = state;
  g_reedQueue[tail].timestamp = timestamp;
  g_reedQueueCount++;
}

// Attempts to deliver every queued transition, oldest first, stopping (and
// preserving order) at the first one that fails so it's retried - in
// order - on a later wake instead of letting later entries jump ahead.
static void drainReedQueue() {
  while (g_reedQueueCount > 0) {
    ReedTransition &t = g_reedQueue[g_reedQueueHead];
    time_t ts =
        (t.timestamp != 0) ? t.timestamp : (Time.isValid() ? Time.now() : 0);
    if (!publishReedChanged(t.state, ts)) {
      Log.warn("reed_changed queue drain stopped (%d entries left) - will "
               "retry in %lu ms",
               (int)g_reedQueueCount, RETRY_INTERVAL_MS);
      break;
    }
    g_reedQueueHead = (g_reedQueueHead + 1) % REED_QUEUE_CAPACITY;
    g_reedQueueCount--;
  }
}

// Whether anything is still waiting to go out that we are willing to power the
// modem up for on its own.
//
// The two events are deliberately not equals here. A reed transition is the
// one thing in this firmware that genuinely has to land, so it qualifies until
// it does, however many attempts that takes. Telemetry only qualifies while
// its slot still has attempts left; after that it waits for the next slot
// rather than keeping the radio busy for a report that will be superseded in
// six hours anyway.
static bool reportPending() {
  return g_reedQueueCount > 0 || (telemetryOwed() && telemetryWithinBudget());
}

// HIBERNATE would be the deepest option, but it requires an external RTC
// chip (AM1815/AM18x5) to generate the wakeup - that's on Particle's own
// B-Series Eval Board reference design, not confirmed present on this
// custom carrier board (not visible on the schematic). Without it,
// HIBERNATE fails at runtime with SYSTEM_ERROR_NOT_SUPPORTED.
//
// ULTRA_LOW_POWER's RTC-based wakeup uses the nRF52840's own internal
// timer instead, no external chip needed. RAM and program state are
// retained; execution resumes right after this call instead of rebooting -
// no fresh setup() each cycle like HIBERNATE gave us.
//
// INACTIVE_STANDBY (keeping the SARA modem registered through sleep) was
// tried first, but the modem's own idle current with standby is ~9mA
// continuous - Device OS deliberately disables the SARA's 3GPP PSM (real
// deep sleep) in software (it caused reliability problems in the past, see
// disablePsmEdrx() upstream), so standby never gets below that ~9mA floor.
// For a report cadence of a few times a day, 9mA continuously between
// reports costs far more energy than fully powering the modem off and
// paying for a cold re-attach (handled entirely by Device OS's own
// registration) each time there's actually something to report.
// Cellular.off() is asynchronous - it dispatches the actual power-down
// (including toggling the modem's UBPWR/UBRST pins) to the system thread and
// returns immediately. Both callers need it to have finished before they go
// on: System.sleep() halts the system thread entirely for the sleep
// duration, and the connect-retry path in loop() would otherwise ask for the
// modem back while it is still going down - either way the power-down
// sequence gets frozen mid-way, leaving the modem in an inconsistent state
// that breaks the next Cellular.on()/reconnect.
//
// Observed via serial log: the async power-down consistently takes close to
// 19s in practice (mux teardown completing ~9s after a 10s wait gave up,
// twice in a row) - 25s gives real margin instead of routinely hitting the
// fallback below.
static void waitForCellularOff() {
  unsigned long offWaitStart = millis();
  while (!Cellular.isOff() && millis() - offWaitStart < 25000) {
    delay(50);
  }
  if (!Cellular.isOff()) {
    Log.info("Cellular didn't confirm off within timeout, continuing anyway");
  }
}

static void sleepWithCellularOff() {
  // Stamp the teardown here rather than waiting for network_status_powering_off
  // to come back through the event queue - that arrives up to six seconds
  // late (see networkStatusHandler()), and those seconds are the difference
  // between the detach being counted as offgoing or as searching. This call
  // is the moment the teardown starts, and we are on the thread that makes it.
  if (s_modemPhase != MODEM_OFF) {
    modemPhaseSet(System.millis(), MODEM_OFFGOING, "Cellular.off()");
  }
  Cellular.off();
  waitForCellularOff();
  // Stop the modem clock before sleeping. On the normal path the
  // network_status_off event has already stopped it during the wait above;
  // this covers the timeout path, where that event hasn't arrived and the
  // clock would otherwise keep running across the entire sleep window and
  // credit all of it to the modem. Under-counting a modem that really did
  // stay powered is the cheaper error of the two - it shows up as current
  // draw either way.
  if (s_modemPhase != MODEM_OFF) {
    modemPhaseSet(System.millis(), MODEM_OFF, "clamped at sleep");
  }
  SystemSleepConfiguration sleepConfig;
  // Wake on either reed edge as well as on the timer, so a transition is
  // reported the moment it happens instead of waiting out the rest of the
  // sleep window. CHANGE covers both directions - open and close are equally
  // worth reporting - and the pin keeps its INPUT_PULLUP from setup() right
  // through sleep, which is what makes the nRF52840's DETECT logic able to
  // see the edge at all (see REED_PIN). The duration stays as the fallback:
  // it re-polls the switch in case an edge was ever missed and it's what
  // paces telemetry.
  sleepConfig.mode(SystemSleepMode::ULTRA_LOW_POWER)
      .duration(WAKE_INTERVAL_MS)
      .gpio(REED_PIN, CHANGE);
  // Brackets the microamp window for an external current trace: this is the
  // last thing on the wire before the drop, and "Woke from sleep" below is
  // the first thing after it. The short delay is what makes that true - the
  // USB CDC write is still draining when System.sleep() would otherwise cut
  // it off, and a truncated line is a lost boundary.
  Log.info("sleeping up to %lu ms", WAKE_INTERVAL_MS);
  delay(20);
  SystemSleepResult result = System.sleep(sleepConfig);
  Log.info("Woke from sleep, reason=%d error=%d", (int)result.wakeupReason(),
           (int)result.error());
  if (result.error() != SYSTEM_ERROR_NONE) {
    // Sleep didn't actually happen (e.g. unexpectedly unsupported config) -
    // fall back to a plain wait instead of spinning the loop with no pacing.
    // Poll the reed while waiting and cut the wait short on a transition, so
    // this path reports just as promptly as the GPIO wake above would have.
    bool reedAtWaitStart = readReedIsClosed();
    unsigned long waitStart = millis();
    while (millis() - waitStart < WAKE_INTERVAL_MS &&
           readReedIsClosed() == reedAtWaitStart) {
      delay(50);
    }
  }
}

// TESTING_MODE skips real sleep entirely (even ULTRA_LOW_POWER can suspend
// USB, dropping a local serial monitor) so remote development/flashing
// stays as uninterrupted as possible. Otherwise sleeps for real; either way
// nothing reboots, so the connect state below persists across cycles.
static void sleepOrIdle() {
  // LED off while asleep - both to save power and so a lit LED reliably
  // means "awake". Hi-Z (INPUT) rather than driving the "off" level: with
  // the pins detached there's no current path through the LED in either
  // wiring polarity, and nothing is actively driven during the sleep
  // window. loop()'s showReedOnLed() call puts them back to OUTPUT with
  // fresh levels first thing on the next wake.
  pinMode(RGBR, INPUT);
  pinMode(RGBG, INPUT);
  pinMode(RGBB, INPUT);
  sleepWithCellularOff();
}

// We only stay connected for a few seconds per wake (see loop()), which
// isn't enough time for an OTA firmware transfer to complete if one lands
// mid-window. This flag lets loop() hold the connection open instead of
// disconnecting/sleeping while a transfer is actually in flight, so a
// pending flash gets a real chance to finish instead of being cut off
// wake after wake.
static volatile bool g_otaInProgress = false;

static void firmwareUpdateHandler(system_event_t event, int param) {
  if (param == firmware_update_begin || param == firmware_update_progress) {
    g_otaInProgress = true;
  } else if (param == firmware_update_complete ||
             param == firmware_update_failed) {
    Log.info("OTA update finished, param=%d", param);
    g_otaInProgress = false;
  }
}

// setup() runs once, when the device is first turned on
void setup() {
  // First line on the wire after a real boot, so a log file can be tied to
  // the exact binary that produced it. Note that waking from ULTRA_LOW_POWER
  // resumes rather than reboots, so this prints once per power-cycle or
  // reset - not once per wake.
  Log.info("=== fw v%d commit=%s | Device OS %s | wake=%lums telemetry=%lus "
           "window=%lus retry=%lums",
           FIRMWARE_VERSION, GIT_COMMIT_SHA, System.version().c_str(),
           WAKE_INTERVAL_MS, (unsigned long)TELEMETRY_PERIOD_S,
           (unsigned long)TELEMETRY_WINDOW_S, RETRY_INTERVAL_MS);
  // Logs this device's slot on the first call, so the offset a report is
  // expected at is in the boot banner rather than only in the payload.
  telemetrySlotOffsetS();

  System.on(firmware_update, firmwareUpdateHandler);
  System.on(network_status, networkStatusHandler);

  // Enabled once and left on for good - the sleep wake source needs it (see
  // REED_PIN).
  pinMode(REED_PIN, INPUT_PULLUP);

  // No BLE antenna on this board - keep the radio fully off.
  BLE.off();

  // We don't use NFC. Left floating, these two pins can settle at different
  // logic levels from each other, which the nRF52840 datasheet documents as
  // causing elevated leakage current (INFC_LEAK) between them. Pulling both
  // down to the same level avoids it. Only SoM platforms expose these pins
  // (a Boron used as a bench test target doesn't define them).
#if PLATFORM_ID == PLATFORM_BSOM
  pinMode(NFC_PIN1, INPUT_PULLDOWN);
  pinMode(NFC_PIN2, INPUT_PULLDOWN);
#endif
}

// loop() runs over and over again, as quickly as it can execute.
void loop() {
  // Cleared per reporting session, so the modem is asked at most once per
  // session but a read that didn't come back still gets another chance.
  static bool checkedOperatorMode = false;
  // Latched for good the first time the modem answers that it is not in
  // manual operator selection - nothing in this firmware can put it back,
  // so from then on there is nothing left to check. Deliberately not reset
  // when a new session begins.
  static bool operatorModeSettled = false;
  static bool firmwareInfoPublished = false;
  static unsigned long wakeStart = millis();
  // Paces retries. Set when an attempt ends having left something
  // undelivered, so the next one waits out RETRY_INTERVAL_MS with the modem
  // off instead of starting straight away; cleared as soon as a wake finds
  // nothing left to report, so the first attempt on genuinely new work is
  // immediate rather than serving out a backoff it didn't earn.
  static unsigned long lastAttemptEndMs = 0;
  static bool retryGateArmed = false;
  // Whether this wake has already committed to connecting. Reed polling
  // itself is just a GPIO read (see readReedIsClosed()), so most wakes never
  // need to set this and go straight back to sleep without touching the radio.
  static bool reporting = false;
  // Set the moment we notice an OTA transfer in progress, so we can bound
  // how long we're willing to wait for it (see MAX_OTA_WAIT_MS).
  static unsigned long otaWaitStart = 0;
  // Set once we've finished publishing for this session, so we can linger
  // connected for a bit (see POST_REPORT_LINGER_MS) instead of disconnecting
  // the instant our own publish call returns.
  static unsigned long reportDoneAt = 0;
  // lastReedState here only tracks "what we last saw at poll time", for
  // edge detection - it does NOT track delivery. Delivery is tracked
  // independently by the ReedTransition queue above, so a transition that
  // fails to publish and then reverts before the next wake isn't silently
  // lost (see enqueueReedTransition()/drainReedQueue()).
  static bool lastReedState = readReedIsClosed();
  // Force one reed_changed report on first boot, even though the initial
  // reading trivially matches itself (see lastReedState above) - otherwise
  // the very first known reed state would never get queued.
  static bool firstPollThisBoot = true;
  static float vBatIdle = 0.;
  bool reedState = readReedIsClosed();
  // Relight the LED with the fresh reading every pass - covers both waking
  // from sleep (sleepOrIdle() turned it off) and a flip mid-session.
  // showReedOnLed(reedState);

  // Detect transitions on every wake (not just when we decide to report)
  // and queue them immediately - this must happen regardless of whether
  // this wake ends up connecting, so a flip that happens while we're mid-
  // session (still connecting, or draining the queue) is captured too.
  if (firstPollThisBoot || reedState != lastReedState) {
    firstPollThisBoot = false;
    lastReedState = reedState;
    enqueueReedTransition(reedState, Time.isValid() ? Time.now() : 0);
  }

  if (!reporting) {
    // Give the slot its attempts back first if we've rolled into a new one,
    // so the budget check below sees the current slot's state, not the one
    // we gave up on.
    telemetryBudgetRollover();

    if (!reportPending()) {
      // Nothing to report this wake - skip Cellular/cloud entirely.
      retryGateArmed = false;
      sleepOrIdle();
      return;
    }

    if (retryGateArmed && millis() - lastAttemptEndMs < RETRY_INTERVAL_MS) {
      // Still inside the gap after an attempt that left something behind.
      //
      // A transition that arrives in here waits for the scheduled retry
      // rather than triggering one of its own: the network that refused us
      // minutes ago is the same network now, and a chattering reed would
      // otherwise hold the modem on continuously. It costs a transition up to
      // RETRY_INTERVAL_MS of extra latency, but only ever one that lands
      // while we are already failing to connect.
      sleepOrIdle();
      return;
    }

    reporting = true;
    wakeStart = millis();
    checkedOperatorMode = false;
    otaWaitStart = 0;
    reportDoneAt = 0;
    vBatIdle = readBatteryVoltage();
    // Spend one of the slot's attempts if telemetry is part of why we're
    // connecting. The budget check is what keeps a session opened purely for
    // a reed transition from counting against a slot that has already given
    // up - telemetry rides along on those for free (see below), but doesn't
    // pay for them.
    if (telemetryOwed() && g_telemetryAttempts < TELEMETRY_MAX_ATTEMPTS) {
      g_telemetryAttempts++;
      Log.info("Telemetry attempt %d/%d for this slot",
               (int)g_telemetryAttempts, TELEMETRY_MAX_ATTEMPTS);
    }
    g_cloudConnectAttemptsCount = g_cloudConnectAttemptsCount >= UINT32_MAX
                                      ? UINT32_MAX
                                      : g_cloudConnectAttemptsCount + 1;
    // Same reasoning as the teardown stamp in sleepWithCellularOff(): this
    // is the moment the modem starts drawing, and network_status_powering_on
    // only reaches the handler a pump later.
    if (s_modemPhase == MODEM_OFF) {
      modemPhaseSet(System.millis(), MODEM_SEARCH, "Particle.connect()");
    }
    Particle.connect();
  }

  // Registration itself is left entirely to Device OS, which escalates on
  // its own (AT+COPS=0,2 PLMN reselection once registration goes sticky, an
  // RF reset via CFUN cycling when it is denied, a modem reset at its
  // 10-minute REGISTRATION_TIMEOUT). The only thing we do ourselves is the
  // one-shot manual-selection cleanup below, held off for a few seconds so
  // the modem is actually up before we talk to it directly.
  if (!Cellular.ready() && !operatorModeSettled && !checkedOperatorMode &&
      millis() - wakeStart > 5000) {
    checkedOperatorMode = true;
    operatorModeSettled = restoreAutomaticOperatorSelection();
  }

  if (Particle.connected()) {
    if (!firmwareInfoPublished) {
      firmwareInfoPublished = true;
      Particle.publish("firmware_info",
                       String::format("{\"version\":%d,\"commit\":\"%s\"}",
                                      FIRMWARE_VERSION, GIT_COMMIT_SHA),
                       PRIVATE);
    }
    // Deliver every queued reed transition, oldest first - stops (and
    // preserves order) at the first failure, retried next wake.
    drainReedQueue();

    // telemetryOwed() rather than the budget-aware reportPending(): while
    // we're connected the report is free, so a slot that has already spent
    // its three attempts still gets sent if a reed transition happened to
    // open a session. What the budget governs is powering the modem up for
    // telemetry alone, not what we do once it is up.
    if (telemetryOwed()) {
      // Neither sleepOrIdle() path reboots (ULTRA_LOW_POWER retains state,
      // same as the plain-delay TESTING_MODE path), so setup() never re-runs
      // to give us a fresh reading - refresh it right before each send.
      float vBatLoad = readBatteryVoltage();
      // Logged rather than published: the cloud already gets the operator and
      // the cell identity in vitals, and this is the level of detail you only
      // want when you are looking at a serial capture next to a current trace.
      logCellularDetails();
      CellularSignal sig = Cellular.RSSI();
      if (publishTelemetry(reedState, vBatLoad, vBatIdle, sig.getStrength(),
                           sig.getQuality())) {
        recordTelemetrySent();
      }
      // A publish the cloud never acknowledged leaves the slot unreported on
      // purpose. This attempt is already spent (counted when the session
      // opened), so the next one comes in RETRY_INTERVAL_MS, or - once the
      // budget is gone - in the next slot.
    }
    // Nothing publishes vitals here on purpose. The cloud requests them
    // itself on every full handshake - Device OS says so in as many words
    // at system_cloud_internal.cpp:1316 ("Vitals are requested by DS only
    // when full handshake is performed"), and it shows up in the serial log
    // as "Received DESCRIBE request; flags: 0x04" (DESCRIBE_METRICS). The
    // clearSession(true) below forces a full handshake on every single
    // connect, so every session that gets this far already emits exactly
    // one spark/device/diagnostics/update - whether this session was for
    // telemetry, a reed transition, or both.
    //
    // An explicit Particle.publishVitals(NOW) used to sit inside the
    // telemetry branch above and made it two per session, one of them
    // redundant. If clearSession(true) ever goes away and sessions start
    // resuming, the cloud stops asking and the explicit call has to come
    // back - the two are coupled.

    if (g_otaInProgress) {
      if (otaWaitStart == 0) {
        otaWaitStart = millis();
      }
      if (millis() - otaWaitStart > MAX_OTA_WAIT_MS) {
        // Transfer stalled without ever reporting complete/failed - give up
        // waiting rather than never sleeping again. Device OS discards an
        // incomplete/unvalidated update on its own, so bailing here is safe;
        // worst case the push just gets retried on a later connection.
        Log.info("Giving up waiting on OTA transfer after %lu ms",
                 millis() - otaWaitStart);
        g_otaInProgress = false;
      } else {
        // A firmware transfer is actively landing - hold the connection open
        // instead of disconnecting/sleeping out from under it.
        delay(1000);
        return;
      }
    }
    otaWaitStart = 0; // not (or no longer) in progress - clear for next time

    if (reportDoneAt == 0) {
      reportDoneAt = millis();
    }
    if (millis() - reportDoneAt < POST_REPORT_LINGER_MS) {
      // Give the cloud a short window to start a pending OTA push - see
      // POST_REPORT_LINGER_MS - before we tear the connection down.
      delay(500);
      return;
    }

    if (g_otaInProgress) {
      // The system thread can set this at any point, including during the
      // linger above - let the g_otaInProgress branch handle waiting it out
      // on the next pass instead of disconnecting right on top of it.
      delay(500);
      return;
    }

    // Done reporting for this wake - drop the cloud session (Cellular stays
    // attached, sleepOrIdle() below puts it in standby) so idle wakes go
    // back to being radio-silent instead of SEMI_AUTOMATIC auto-maintaining
    // the connection we just opened.
    //
    // clearSession(true): without this, the next connect resumes the DTLS
    // session and skips the full Hello/Describe handshake whenever nothing
    // in our own subscriptions/app-describe state has changed - and that
    // skip is governed by state bits we have no clean way to force from
    // application code (confirmed by tracing protocol.cpp: subscribing to
    // a new event name, tried previously, doesn't affect this at all).
    // Clearing the session on every disconnect instead forces a genuine
    // full handshake on the very next connect - the same effect a physical
    // reset gives, without needing one - so the cloud always gets a real
    // chance to check for and push a pending OTA update.
    g_cloudConnectSuccesses = g_cloudConnectSuccesses >= UINT32_MAX
                                  ? UINT32_MAX
                                  : g_cloudConnectSuccesses + 1;
    Particle.disconnect(CloudDisconnectOptions().clearSession(true));
    reporting = false;
    // Arm the retry gate only if this session actually left something behind -
    // a reed entry whose publish failed, or a telemetry report that wasn't
    // acknowledged and still has attempts left. A session that got everything
    // out leaves the gate open so the next transition connects immediately.
    lastAttemptEndMs = millis();
    retryGateArmed = reportPending();
    sleepOrIdle();
  } else if (millis() - wakeStart > MAX_CONNECT_WAIT_MS) {
    // This attempt is out of budget. End it here and sleep, rather than
    // power-cycling the modem and starting a fresh registration on the spot
    // the way earlier builds did for as long as anything was queued.
    //
    // That earlier behaviour was the right trade for a handful of devices -
    // a transition landed the moment coverage came back - and the wrong one
    // for a fleet of thousands. The failure that stops one device from
    // registering is usually the one stopping its neighbours too, so
    // answering an outage by holding every modem on continuously is both the
    // most expensive possible response and the one that makes the recovery
    // hardest, all of them hammering the cell the instant it returns.
    // RETRY_INTERVAL_MS paces the next attempt instead, and sleepOrIdle()
    // below powers the modem down (Cellular.off() plus the wait for it to
    // confirm) on the way into sleep - which is also what makes that next
    // attempt a genuinely cold registration rather than a continuation of
    // the one that just failed. A reed transition still gets unlimited
    // attempts; they are just spaced now.
    Log.info("Connect attempt timed out after %lu ms - modem off, retrying in "
             "%lu ms",
             millis() - wakeStart, RETRY_INTERVAL_MS);
    Particle.disconnect(CloudDisconnectOptions().clearSession(true));
    reporting = false;
    lastAttemptEndMs = millis();
    retryGateArmed = true;
    sleepOrIdle();
  } else {
    delay(1000);
  }
}
